<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
//$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);

// Set platform
$platform = Pi::service('browser')->getPlatform();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<header class="pi-header">
    <?php if ($platform == 'Android') { ?>
        <div class="pi-header-app">
            <a href="https://play.google.com/store/apps/details?id=com.faragostaresh.cafeyab" title="دریافت از گوگل پلی" >
                <img src="<?php echo $this->assetTheme('image/app-android.png'); ?>" alt="دریافت از گوگل پلی">
            </a>
        </div>
    <?php } elseif (in_array($platform, array('iPhone', 'iPad', 'Ios'))) { ?>
        <div class="pi-header-app">
            <a href="https://itunes.apple.com/us/app/cafeyab-kafh-yab/id1071729005?ls=1&mt=8" title="دریافت از اپ استور">
                <img src="<?php echo $this->assetTheme('image/app-ios.png'); ?>" alt="دریافت از اپ استور">
            </a>
        </div>
    <?php } ?>
    <div class="pi-header-top">
        <div class="container">
            <div class="row">
                <div class="pi-header-user col-md-6 col-xs-12 animated fadeInDown">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
                <div class="pi-header-search col-md-6 col-xs-12 text-right animated slideInLeft">
                    <?php echo $this->widget('search-search'); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-header-body">
        <div class="container">
            <div class="row">
                <nav class="pi-header-menu col-md-12" itemscope itemtype="http://schema.org/SiteNavigationElement">
                    <div class="navbar navbar-default yamm">
                        <div class="navbar-header">
                            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <i class="fa fa-bars"></i>
                            </button>
                            <div class="pi-header-logo animated fadeInRight">
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                    <img src="<?php echo $this->logo(); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </div>
                            <div class="pi-header-title animated fadeInDown">
                                <?php if ($module == 'system') { ?>
                                    <h1 itemprop="name">
                                        <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                            <?php echo _escape($sitename); ?>
                                        </a>
                                    </h1>
                                <?php } else { ?>
                                    <h2 itemprop="name">
                                        <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                            <?php echo _escape($sitename); ?>
                                        </a>
                                    </h2>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav pi-navbar-nav animated fadeInUp">
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>guide" title="فهرست کافه‌ها">
                                        <span itemprop="name">فهرست کافه‌ها</span>
                                    </a>
                                </li>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>guide/map" title="کافه‌ها روی نقشه">
                                        <span itemprop="name">کافه‌ها روی نقشه</span>
                                    </a>
                                </li>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>video" title="ویدیو">
                                        <span itemprop="name">ویدیو</span>
                                    </a>
                                </li>
                                <?php /* if (!in_array($platform, array('Android', 'iPhone', 'iPad', 'Ios'))) { ?>
                                    <li class="dropdown yamm-fw">
                                        <a aria-expanded="false" itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop" title="محصولات تخصصی" data-toggle="dropdown" class="dropdown-toggle dropdown-toggle-shop"><span itemprop="name">محصولات تخصصی</span> <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li class="grid-menu">
                                                <div class="row">
                                                    <div class="col-sm-3">
                                                        <h4><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/Coffee" title="قهوه">قهوه</a></h4>
                                                        <ul class="list-unstyled">
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/essse-coffee" title="اسسه Essse">اسسه Essse ( پیشنهاد کافه‌یاب )</a></li>

                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/caffe-mauro" title="مائورو Mauro">مائورو Mauro</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/vergnano" title="ورنیانو Vergnano">ورنیانو Vergnano</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/julius-meinl" title="ژولیوس Julius Meinl">ژولیوس Julius Meinl</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/kimbo" title="کیمبو Kimbo">کیمبو Kimbo</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/lamiz-coffee" title="لمیز کافی Lamiz coffee">لمیز کافی Lamiz coffee</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-sm-3">
                                                        <h4><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/Coffee-makers" title="قهوه‌ساز‌ها">قهوه‌ساز‌ها</a></h4>
                                                        <ul class="list-unstyled">
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/handpresso" title="هندپرسو Handpresso">هندپرسو Handpresso</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/handcoffee" title="هند‌کافی Handcoffee">هند‌کافی Handcoffee</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/cafflano" title="کافلانو Cafflano">کافلانو Cafflano</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/syphon-vacuum-coffee-maker" title="سایفون Syphon">سایفون Syphon</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/french-press" title="فرنچ پرس French Press">فرنچ پرس French Press</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/chemex" title="کمکس Chemex">کمکس Chemex</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/Nespresso" title="نسپرسو Nespresso">نسپرسو Nespresso</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/Capsule-espresso-machine" title="اسپرسوساز کپسولی">اسپرسوساز کپسولی</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/coffeemakers-filter" title="فیلتر">فیلتر</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-sm-3">
                                                        <h4><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/syrup" title="طعم‌دهنده(سیروپ)">طعم‌دهنده(سیروپ)</a></h4>
                                                        <ul class="list-unstyled">
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/torani" title="تورانی Torani">تورانی Torani</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/monin" title="مونین Monin">مونین Monin</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-sm-3">
                                                        <h4>سایر محصولات</h4>
                                                        <ul class="list-unstyled">
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/herbal-tea" title="دمنوش و چای">دمنوش و چای</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/grinder" title="آسیاب(گرایندر)">آسیاب(گرایندر)</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/cafeyab-packages" title="بسته‌های کافه‌یاب">بسته‌های کافه‌یاب</a></li>
                                                            <li><a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop/mug-and-cups" title="ماگ و فنجان">ماگ و فنجان</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                <?php } else { ?>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop" title="محصولات تخصصی">
                                            <span itemprop="name">محصولات تخصصی</span>
                                        </a>
                                    </li>
                                <?php } */ ?>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>shop" title="محصولات تخصصی">
                                        <span itemprop="name">محصولات تخصصی</span>
                                    </a>
                                </li>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>event" title="رویداد‌ها">
                                        <span itemprop="name">رویداد‌ها</span>
                                    </a>
                                </li>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>plans" title="بسته ها">
                                        <span itemprop="name">بسته ها</span>
                                    </a>
                                </li>
                                <li>
                                    <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>news" title="مطالب">
                                        <span itemprop="name">مطالب</span>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right pi-navbar-nav animated fadeInUp">
                                <?php /* <li>
                                    <?php echo $this->widget('shop-basket'); ?>
                                </li> */ ?>
                                <li class="active">
                                    <a itemprop="url" class="btn btn-primary" href="<?php echo Pi::url($this->url('home')); ?>guide/manage" title="ثبت و مدیریت کافه">
                                        <span itemprop="name">ثبت و مدیریت کافه</span>
                                    </a>
                                </li>
                            </ul>
                            <?php if (in_array($platform, array('Android', 'iPhone', 'iPad', 'Ios'))) { ?>
                            <div class=clearfix">
                                <?php echo $this->widget('system-user-bar'); ?>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<section class="pi-section">
    <?php if (isset($blocks['99'])) { ?>
        <div class="pi-top-container">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 pi-zone-8">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="pi-main-container">
        <div class="container">
            <!--[if lt IE 9]>
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <h4>خطا در نمایش وب سایت</h4>
                        <p>مرورگر اینترنت شما قدیمی است و از تکنولوژی های جدید وب پشتیبانی نمی کند. برای استفاده از این وب سایت مرورگر خود را به روز کنید.</p>
                        <p>شما میتوانید از مرورگر های <a href="https://www.mozilla.org/en-US/firefox/new/" >فایرفاکس</a> یا <a href="https://www.google.com/chrome">گوگل کروم</a> استفاده نمایید.</p>
                    </div>
                </div>
            </div>
            <![endif]-->
            <?php if (!in_array($platform, array('Android', 'iPhone', 'iPad', 'Ios'))) { ?>
                <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <?php } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <?php if (in_array($platform, array('Android', 'iPhone', 'iPad', 'Ios'))) { ?>
                <div class="clearfix">
                    <div class="row">
                        <div class="col-xs-12">
                            <?php echo $this->widget('search-search'); ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <!-- Top head zone -->
            <?php if (!empty($blocks['0'])) { ?>
                <div class="pi-zone-0">
                    <?php foreach ($blocks['0'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php if ($module != 'page') {
                                echo Pi::service('comment')->load(array('options' => array('type' => 'js')));
                            } ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Center bottom zone -->
                    <?php if (isset($blocks['7'])) { ?>
                        <div class="pi-zone-7">
                            <?php foreach ($blocks['7'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                        <?php if ($module == 'system') { ?>
                            <div class="pi-block ">
                                <div class="pi-block-title">
                                    <h2>گواهینامه ها</h2>
                                </div>
                                <div class="pi-block-content">
                                    <div class="clearfix text-center">
                                        <div class="col-md-6 col-sm-6 col-xs-6">
                                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="به پرداخت">
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6">
                                            <img id='wmcshwlanbpedrft' onclick='window.open("https://trustseal.enamad.ir/Verify.aspx?id=8421&p=aqgwodshwkynnbpd", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' alt='نماد اعتماد الکترونیک' src='https://trustseal.enamad.ir/logo.aspx?id=8421&p=ukaqaodsqesglznb'/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</section>
<!-- Bottom foot zone -->
<?php if (!in_array($platform, array('Android', 'iPhone', 'iPad', 'Ios'))) { ?>
    <section class="pi-section-bottom pi-zone-99 hidden-xs">
        <div class="pi-section-app">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 pi-section-app-title text-center">
                        <h2>نرم افزار تلفن همراه کافه یاب</h2>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/app-img.png'); ?>" alt="نرم افزار تلفن همراه کافه یاب">
                    </div>
                    <div class="pi-section-app-text col-md-6 col-sm-6 col-xs-6">

                        <p>نرم افزار اندروید کافه یاب را از گوگل پلی و نرم افزار  آی او اس را از اپ استور دریافت نمایید.</p>
                        <ul class="list-inline text-center">
                            <li>
                                <a href="https://play.google.com/store/apps/details?id=com.faragostaresh.cafeyab" title="دریافت از گوگل پلی" >
                                    <img src="<?php echo $this->assetTheme('image/app-android.png'); ?>" alt="دریافت از گوگل پلی">
                                </a>
                            </li>
                            <li><a href="https://itunes.apple.com/us/app/cafeyab-kafh-yab/id1071729005?ls=1&mt=8" title="دریافت از اپ استور" >
                                    <img src="<?php echo $this->assetTheme('image/app-ios.png'); ?>" alt="دریافت از اپ استور">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php } ?>
<footer class="pi-footer">
    <div class="pi-footer-body">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <ul class="list-unstyled">
                            <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                            <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact"><i class="fa fa-angle-left"></i> تماس با ما</a></li>
                            <li><a title="راهنمای ثبت کافه" href="<?php echo Pi::url($this->url('home')); ?>page/registration-guide"><i class="fa fa-angle-left"></i> راهنمای ثبت کافه</a></li>
                            <li><a title="راهنمای کاربران" href="<?php echo Pi::url($this->url('home')); ?>page/user-guide/"><i class="fa fa-angle-left"></i> راهنمای کاربران</a></li>
                            <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>page/rules"><i class="fa fa-angle-left"></i> قوانین و مقررات</a></li>
                            <li><a title="سوالات متداول" href="https://www.cafeyab.com/page/faq"><i class="fa fa-angle-left"></i> سوالات متداول</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <ul class="list-unstyled">
                            <li><a title="کافه‌ها" href="<?php echo Pi::url($this->url('home')); ?>guide/cafe"><i class="fa fa-angle-left"></i> کافه‌ها</a></li>
                            <li><a title="کافی شاپ ها" href="<?php echo Pi::url($this->url('home')); ?>guide/coffee-shops"><i class="fa fa-angle-left"></i> کافی شاپ ها</a></li>
                            <li><a title="فروشگاه ها" href="<?php echo Pi::url($this->url('home')); ?>guide/shop"><i class="fa fa-angle-left"></i> فروشگاه ها</a></li>
                            <li><a title="شیرینی فروشی ها" href="<?php echo Pi::url($this->url('home')); ?>guide/pastry"><i class="fa fa-angle-left"></i> شیرینی فروشی ها</a></li>
                            <li><a title="کافه‌ها روی نقشه" href="<?php echo Pi::url($this->url('home')); ?>guide/map"><i class="fa fa-angle-left"></i> کافه‌ها روی نقشه</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <ul class="list-unstyled">
                            <li><a title="محصولات تخصصی" href="https://www.cafeyab.com/shop"><i class="fa fa-angle-left"></i> محصولات تخصصی</a></li>
                            <li><a title="قهوه" href="https://www.cafeyab.com/shop/Coffee"><i class="fa fa-angle-left"></i> قهوه</a></li>
                            <li><a title="قهوه‌ساز‌ها" href="https://www.cafeyab.com/shop/Coffee-makers"><i class="fa fa-angle-left"></i> قهوه‌ساز‌ها</a></li>
                            <li><a title="دمنوش و چای" href="https://www.cafeyab.com/shop/herbal-tea"><i class="fa fa-angle-left"></i> دمنوش و چای</a></li>
                            <li><a title="بسته‌های کافه‌یاب" href="https://www.cafeyab.com/shop/cafeyab-packages"><i class="fa fa-angle-left"></i> بسته‌های کافه‌یاب</a></li>
                            <li><a title="شرایط و مقررات خرید کالا و ثبت سفارش" href="https://www.cafeyab.com/page/terms-and-conditions"><i class="fa fa-angle-left"></i> شرایط و مقررات خرید</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="clearfix">
                        <div class="clearfix">کافه‌یاب به عنوان مرجع معرفی و اطلاع‌رسانی کافه‌های ایران، در تابستان ۹۳ فعالیت خود را آغاز نمود. این وب‌سایت در نظر دارد تا با معرفی  <h2>کافه</h2>‌ها، <h2>کافی‌شاپ</h2>‌ها، <h2>شیرینی فروشی</h2>‌ها و <h2>قهوه فروشی</h2>‌ها، امکان آشنایی کاربران را با این مکان‌ها و خدماتشان، فراهم کند. همچنین امکان درج و به روز رسانی اطلاعات کافه‌ها توسط صاحبان آن‌ها در وب‌سایت وجود دارد.</div>
                        <div class="clearfix">تمامی کالاها و خدمات این وب‌سایت، حسب مورد دارای مجوزهای لازم از مراجع مربوطه می‌باشند و فعالیت‌های این وب‌سایت تابع قوانین و مقررات جمهوری اسلامی ایران است. </div>
                    </div>
                    <div class="pi-social">
                        <ul class="list-inline">
                            <li id="pi-social-twitter"><a title="تویتر" href="https://twitter.com/cafeyab" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li id="pi-social-facebook"><a title="فیسبوک" href="https://www.facebook.com/cafeyab" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li id="pi-social-pinterest"><a title="پین‌ترست" href="https://www.pinterest.com/cafeyab" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                            <li id="pi-social-google" class="hidden-xs hidden-sm"><a title="گوگل پلاس" href="https://plus.google.com/+CafeYab" target="_blank" rel="Publisher"><i class="fa fa-google-plus"></i></a></li>
                            <li id="pi-social-instagram"><a title="اینستاگرام" href="https://www.instagram.com/cafe.yab" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            <li id="pi-social-foursquare"><a title="Foursquare" href="https://www.foursquare.com/cafeyab" target="_blank"><i class="fa fa-foursquare"></i></a></li>
                            <li id="pi-social-rss-news" class="hidden-xs hidden-sm"><a title="خوراک اخبار و مقالات" href="<?php echo Pi::url($this->url('home')); ?>feed/news" target="_blank"><i class="fa fa-rss-square"></i></a></li>
                            <li id="pi-social-rss-guide" class="hidden-xs hidden-sm"><a title="خوراک کافه‌ها" href="<?php echo Pi::url($this->url('home')); ?>feed/guide" target="_blank"><i class="fa fa-rss-square"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright">
        <div class="container">
            <div class="row">
                <div class="text-left col-md-6" data-rel="license"> تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="https://www.cafeyab.com"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-md-6" data-rel="license"> طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
<script type="application/ld+json">
{
    "@context" : "http://schema.org",
    "@type" : "WebSite",
    "name" : "<?php echo _escape($sitename); ?>",
    "alternateName" : "کافه‌یاب نگاهیست نو به فرهنگ کافه‌نشینی در ایران، مرجعی برای یافتن یا معرفی و البته سهیم کردن یکدیگر در تجربه حضورمان در آن‌ها",
    "url" : "https://www.cafeyab.com",
    "potentialAction": {
        "@type": "SearchAction",
        "target": "<?php echo Pi::url($this->url('home')); ?>search/?q={search_term_string}",
        "query-input": "required name=search_term_string"
    }
}
</script>
<script type="application/ld+json">
{
    "@context" : "http://schema.org",
    "@type" : "Organization",
    "name" : "<?php echo _escape($sitename); ?>",
    "logo" : "<?php echo $this->logo(); ?>",
    "url" : "https://www.cafeyab.com",
    "sameAs" : [
        "https://www.twitter.com/cafeyab",
        "https://www.facebook.com/cafeyab",
        "https://plus.google.com/+CafeYab",
        "https://www.pinterest.com/cafeyab",
        "https://www.instagram.com/cafe.yab",
        "https://www.foursquare.com/cafeyab"
    ]
}
</script>
</body>
</html>