<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<?php if ($module == 'system') { ?>
    <header class="pi-header">
        <div class="pi-header-body">
            <div class="navbar navbar-inverse clearfix">
                <div class="container-fluid">
                    <div class="row" itemscope itemtype="https://schema.org/SiteNavigationElement">
                        <nav class="col-md-12" >
                            <div class="navbar-header">
                                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav pi-navbar-nav animated fadeInUp">
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/guide" title="کافه‌ها">
                                            <span itemprop="name">کافه‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/guide/map" title="کافه‌ها روی نقشه">
                                            <span itemprop="name">کافه‌ها روی نقشه</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/plans" title="بسته‌ها">
                                            <span itemprop="name">بسته‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/video" title="ویدیو">
                                            <span itemprop="name">ویدیو</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/shop" title="محصولات">
                                            <span itemprop="name">محصولات</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/event" title="رویداد‌ها">
                                            <span itemprop="name">رویداد‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/news" title="مطالب">
                                            <span itemprop="name">مطالب</span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="navbar-right">
                                    <?php echo $this->widget('system-user-bar'); ?>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="pi-header-logo clearfix">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 text-center">
                            <div class="pi-header-box">
                                <div class="clearfix hidden-xs">
                                    <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                        <img src="<?php echo $this->assetTheme('image/logo-home.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                    </a>
                                </div>
                                <h1>کافه یاب</h1>
                                <h2 class="hidden-xs">نگاهیست نو به فرهنگ کافه‌نشینی و قهوه نوشی در ایران، مرجعی برای یافتن یا معرفی و البته سهیم کردن یکدیگر در تجربه حضورمان در آن‌ها</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pi-header-search clearfix">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="text-center hidden-xs">
                                <h2>جستجو در وب سایت، یافتن کافه، شهر و محله، رویداد‌های نزدیک و ...</h2>
                            </div>
                            <?php echo $this->widget('search-search'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-header-image">
            <div class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="active item">
                        <picture>
                            <!--[if IE 9]><video style="display: none;"><![endif]-->
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/header/header-mobi.jpg'); ?>">
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/header/header-smart.jpg'); ?>">
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/header/header-tab.jpg'); ?>">
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/header/header-lap.jpg'); ?>">
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/header/header-xlap.jpg'); ?>">
                            <source data-srcset="<?php echo $this->assetTheme('image/header/header-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/header/header-desk.jpg'); ?>">
                            <!--[if IE 9]></video><![endif]-->
                            <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/header/header-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/header/header-xlap.jpg'); ?>">
                        </picture>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="pi-section">
        <!--[if lt IE 9]>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <h4>خطا در نمایش وب سایت</h4>
                        <p>مرورگر اینترنت شما قدیمی است و از تکنولوژی‌های جدید وب پشتیبانی نمی کند. برای استفاده از این وب سایت مرورگر خود را به روز کنید.</p>
                        <p>شما میتوانید از مرورگر‌های <a href="https://www.mozilla.org/en-US/firefox/new/" >فایرفاکس</a> یا <a href="https://www.google.com/chrome">گوگل کروم</a> استفاده نمایید.</p>
                    </div>
                </div>
            </div>
        </div>
        <![endif]-->
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <?php if (!empty($blocks['0'])) { ?>
            <div class="pi-zone-0">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['0'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php /* <div class="pi-section-image">
                <div class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="active item">
                            <picture>
                                <!--[if IE 9]><video style="display: none;"><![endif]-->
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>">
                                <!--[if IE 9]></video><![endif]-->
                                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                            </picture>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        <?php } ?>
        <?php if (!empty($blocks['1'])) { ?>
            <div class="pi-zone-1">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php /* <div class="pi-section-image">
                <div class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="active item">
                            <picture>
                                <!--[if IE 9]><video style="display: none;"><![endif]-->
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>">
                                <!--[if IE 9]></video><![endif]-->
                                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                            </picture>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        <?php } ?>
        <?php if (isset($blocks['3']) || isset($blocks['4']) || isset($blocks['5'])) { ?>
            <div class="pi-zone-345">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4 pi-zone-3">
                            <?php if (isset($blocks['3'])) {
                                foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                                }
                            } ?>
                        </div>
                        <div class="col-md-4 pi-zone-4">
                            <?php if (isset($blocks['4'])) {
                                foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                                }
                            } ?>
                        </div>
                        <div class="col-md-4 pi-zone-5">
                            <?php if (isset($blocks['5'])) {
                                foreach ($blocks['5'] as $block) {
                                    include $blockTemplate;
                                }
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if (!empty($blocks['6'])) { ?>
            <div class="pi-zone-6">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['6'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if (!empty($blocks['2'])) { ?>
            <div class="pi-zone-2">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php /* <div class="pi-section-image">
                <div class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="active item">
                            <picture>
                                <!--[if IE 9]><video style="display: none;"><![endif]-->
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>">
                                <!--[if IE 9]></video><![endif]-->
                                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                            </picture>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        <?php } ?>
        <?php if (!empty($blocks['99'])) { ?>
            <div class="pi-zone-99">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['99'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php /* <div class="pi-section-image">
                <div class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="active item">
                            <picture>
                                <!--[if IE 9]><video style="display: none;"><![endif]-->
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/section/section-1-mobi.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/section/section-1-smart.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/section/section-1-tab.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/section/section-1-lap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                                <source data-srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/section/section-1-desk.jpg'); ?>">
                                <!--[if IE 9]></video><![endif]-->
                                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/section/section-1-xlap.jpg'); ?>">
                            </picture>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        <?php } ?>
        <?php if (isset($blocks['7'])) { ?>
            <div class="pi-zone-7">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($blocks['7'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </section>
<?php } else { ?>
    <header class="pi-header">
        <div class="pi-header-body">
            <div class="navbar navbar-inverse clearfix">
                <div class="container-fluid">
                    <div class="row" itemscope itemtype="https://schema.org/SiteNavigationElement">
                        <nav class="col-md-12" >
                            <div class="navbar-header">
                                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>" rel="home">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav pi-navbar-nav animated fadeInUp">
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/guide" title="کافه‌ها">
                                            <span itemprop="name">کافه‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/guide/map" title="کافه‌ها روی نقشه">
                                            <span itemprop="name">کافه‌ها روی نقشه</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/plans" title="بسته‌ها">
                                            <span itemprop="name">بسته‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/video" title="ویدیو">
                                            <span itemprop="name">ویدیو</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/shop" title="محصولات">
                                            <span itemprop="name">محصولات</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/event" title="رویداد‌ها">
                                            <span itemprop="name">رویداد‌ها</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a itemprop="url" href="<?php echo Pi::url($this->url('home')); ?>/news" title="مطالب">
                                            <span itemprop="name">مطالب</span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="navbar-right">
                                    <?php echo $this->widget('system-user-bar'); ?>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4">
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                <?php echo _escape($sitename); ?>
                            </a>
                        </h2>
                    </div>
                    <div class="col-md-4 col-md-offset-2">
                        <div class="pi-header-search">
                            <?php echo $this->widget('search-search'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section class="pi-section">
        <div class="container-fluid">
            <div class="pi-main-container">
                <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<!-- Bottom foot zone -->
<section class="pi-section-bottom">
    <div class="pi-section-app">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 pi-section-app-title text-center">
                    <h2>نرم افزار تلفن همراه کافه یاب</h2>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <img class="img-responsive" src="<?php echo $this->assetTheme('image/app-img.png'); ?>" alt="نرم افزار تلفن همراه کافه یاب">
                </div>
                <div class="pi-section-app-text col-md-6 col-sm-6 col-xs-12 text-center">
                    <p class="text-center">نرم افزار اندروید کافه یاب را از گوگل پلی و نرم افزار  آی او اس را از اپ استور دریافت نمایید.</p>
                    <ul class="list-inline">
                        <li>
                            <a href="https://play.google.com/store/apps/details?id=com.faragostaresh.cafeyab" title="دریافت از گوگل پلی" >
                                <img src="<?php echo $this->assetTheme('image/app-android.png'); ?>" alt="دریافت از گوگل پلی">
                            </a>
                        </li>
                        <li>
                            <a href="https://itunes.apple.com/us/app/cafeyab-kafh-yab/id1071729005?ls=1&mt=8" title="دریافت از اپ استور" >
                                <img src="<?php echo $this->assetTheme('image/app-ios.png'); ?>" alt="دریافت از اپ استور">
                            </a>
                        </li>
                    </ul>
                    <ul class="list-inline">
                        <li>
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="به پرداخت">
                        </li>
                        <li>
                            <img class="img-responsive" id='wmcshwlanbpedrft' onclick='window.open("https://trustseal.enamad.ir/Verify.aspx?id=8421&p=aqgwodshwkynnbpd", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' alt='نماد اعتماد الکترونیک' src='https://trustseal.enamad.ir/logo.aspx?id=8421&p=ukaqaodsqesglznb'/>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<footer class="pi-footer">
    <div class="pi-footer-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="pi-social">
                        <ul class="list-inline">
                            <li id="pi-social-twitter"><a title="تویتر" href="https://twitter.com/cafeyab" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li id="pi-social-facebook"><a title="فیسبوک" href="https://www.facebook.com/cafeyab" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li id="pi-social-pinterest"><a title="پین‌ترست" href="https://www.pinterest.com/cafeyab" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                            <li id="pi-social-google" class="hidden-xs hidden-sm"><a title="گوگل پلاس" href="https://plus.google.com/+CafeYab" target="_blank" rel="Publisher"><i class="fa fa-google-plus"></i></a></li>
                            <li id="pi-social-instagram"><a title="اینستاگرام" href="https://www.instagram.com/cafe.yab" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            <li id="pi-social-foursquare"><a title="Foursquare" href="https://www.foursquare.com/cafeyab" target="_blank"><i class="fa fa-foursquare"></i></a></li>
                            <li id="pi-social-rss-news" class="hidden-xs hidden-sm"><a title="خوراک اخبار و مقالات" href="<?php echo Pi::url($this->url('home')); ?>/feed/news" target="_blank"><i class="fa fa-rss-square"></i></a></li>
                            <li id="pi-social-rss-guide" class="hidden-xs hidden-sm"><a title="خوراک کافه‌ها" href="<?php echo Pi::url($this->url('home')); ?>/feed/guide" target="_blank"><i class="fa fa-rss-square"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-12 col-xs-12">
                    <div class="pi-footer-text">
                        <div class="clearfix">کافه‌یاب به عنوان مرجع معرفی و اطلاع‌رسانی کافه‌های ایران، در تابستان ۹۳ فعالیت خود را آغاز نمود. این وب‌سایت در نظر دارد تا با معرفی <h2>کافه</h2>‌ها، <h2>کافی‌شاپ</h2>‌ها، <h2>شیرینی فروشی</h2>‌ها و <h2>قهوه فروشی</h2>‌ها، امکان آشنایی کاربران را با این مکان‌ها و خدماتشان، فراهم کند. همچنین امکان درج و به روز رسانی اطلاعات کافه‌ها توسط صاحبان آن‌ها در وب‌سایت وجود دارد.</div>
                        <div class="clearfix">تمامی کالاها و خدمات این وب‌سایت، حسب مورد دارای مجوزهای لازم از مراجع مربوطه می‌باشند و فعالیت‌های این وب‌سایت تابع قوانین و مقررات جمهوری اسلامی ایران است.</div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">
                    <ul class="list-unstyled">
                        <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>/page/about-us">درباره ما</a></li>
                        <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>/contact">تماس با ما</a></li>
                        <li><a title="سوالات متداول" href="<?php echo Pi::url($this->url('home')); ?>/page/faq">سوالات متداول</a></li>
                        <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>/page/rules">قوانین و مقررات</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <ul class="list-unstyled">
                        <li><a title="فهرست کافه‌ها" href="<?php echo Pi::url($this->url('home')); ?>/guide">فهرست کافه‌ها</a></li>
                        <li><a title="کافه‌ها روی نقشه" href="<?php echo Pi::url($this->url('home')); ?>/guide/map">کافه‌ها روی نقشه</a></li>
                        <li><a title="ثبت و مدیریت کافه" href="<?php echo Pi::url($this->url('home')); ?>/guide/manage">ثبت و مدیریت کافه</a></li>
                        <li><a title="راهنمای ثبت کافه" href="<?php echo Pi::url($this->url('home')); ?>/page/registration-guide">راهنمای ثبت کافه</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <ul class="list-unstyled">
                        <li><a title="رویداد‌ها" href="<?php echo Pi::url($this->url('home')); ?>/">رویداد‌ها</a></li>
                        <li><a title="ویدیو‌ها" href="<?php echo Pi::url($this->url('home')); ?>/">ویدیو‌ها</a></li>
                        <li><a title="مطالب" href="<?php echo Pi::url($this->url('home')); ?>/">مطالب</a></li>
                        <li><a title="بسته‌های تبلیغاتی" href="<?php echo Pi::url($this->url('home')); ?>/plans">بسته‌های تبلیغاتی</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-xs-12">
                    <ul class="list-unstyled">
                        <li><a title="محصولات" href="<?php echo Pi::url($this->url('home')); ?>/shop">محصولات</a></li>
                        <li><a title="قهوه" href="<?php echo Pi::url($this->url('home')); ?>/shop/coffee">قهوه</a></li>
                        <li><a title="قهوه‌ساز‌ها" href="<?php echo Pi::url($this->url('home')); ?>/shop/coffee-makers">قهوه‌ساز‌ها</a></li>
                        <li><a title="بسته‌های کافه‌یاب" href="<?php echo Pi::url($this->url('home')); ?>/shop/cafeyab-packages">بسته‌های کافه‌یاب</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright">
        <div class="container-fluid">
            <div class="row">
                <div class="text-left col-md-6" data-rel="license"> تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-md-6" data-rel="license"> طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
<script type="application/ld+json">
{
    "@context" : "https://schema.org",
    "@type" : "WebSite",
    "name" : "<?php echo _escape($sitename); ?>",
    "alternateName" : "کافه‌یاب نگاهیست نو به فرهنگ کافه‌نشینی در ایران، مرجعی برای یافتن یا معرفی و البته سهیم کردن یکدیگر در تجربه حضورمان در آن‌ها",
    "url" : "<?php echo Pi::url($this->url('home')); ?>",
    "potentialAction": {
        "@type": "SearchAction",
        "target": "<?php echo Pi::url($this->url('home')); ?>/search/?q={search_term_string}",
        "query-input": "required name=search_term_string"
    }
}
</script>
<script type="application/ld+json">
{
    "@context" : "https://schema.org",
    "@type" : "Organization",
    "name" : "<?php echo _escape($sitename); ?>",
    "logo" : "<?php echo $this->logo(); ?>",
    "url" : "<?php echo Pi::url($this->url('home')); ?>",
    "sameAs" : [
        "https://www.twitter.com/cafeyab",
        "https://www.facebook.com/cafeyab",
        "https://plus.google.com/+CafeYab",
        "https://www.pinterest.com/cafeyab",
        "https://www.instagram.com/cafe.yab",
        "https://www.foursquare.com/cafeyab"
    ]
}
</script>
</body>
</html>