<?php
$userSection = $this->isUserSection(Pi::service('module')->current());
$originalBlockType = $block['type'];

if($block['type'] == 'mixed' || $block['type'] == 'mixed_light'){
    $block['type'] = $userSection ? 'flat' : 'dropdown';
}
$floatClass = ($block['float'] == 'left') ? '' : ' navbar-right';

$modalEnabled = Pi::user()->config('enable_modal');
?>
<div class="user-bar">
    <div class="navbar navbar-default">
        <ul class="nav navbar-nav pi-navbar-nav">
            <?php if (!$block['user']['uid']) { ?>
                <li class="item-login">
                    <a href="<?php echo $modalEnabled ? '#' : $block['user']['login'] ?>" data-target="#loginRegisterModal" data-action="login" <?php if($modalEnabled) : ?>data-toggle="modal"<?php endif; ?> title="<?php echo _b('Login'); ?>">
                        <i class="fa fa-sign-in"></i>
                        <span class="hidden-sm hidden-md"><?php echo _b('Login'); ?></span>
                    </a>
                </li>
                <li class="item-register">
                    <a href="<?php echo $modalEnabled ? '#' : $block['user']['register'] ?>" data-target="#loginRegisterModal" data-action="register" <?php if($modalEnabled) : ?>data-toggle="modal"<?php endif; ?> title="<?php echo _b('Register'); ?>">
                        <?php echo _b('Register'); ?>
                    </a>
                </li>
            <?php } else { ?>
                <li class="dropdown">
                    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $block['user']['avatar']; ?>
                        <?php echo _escape($block['user']['name']); ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a title="پیگیری سفارش ها" href="https://www.cafeyab.com/order">پیگیری سفارش ها</a></li>
                        <li><a title="فهرست علاقه مندی ها" href="https://www.cafeyab.com/guide/favourite">فهرست علاقه مندی ها</a></li>
                        <li><a title="تنظیمات حساب کاربری" href="https://www.cafeyab.com/user/account/">تنظیمات حساب کاربری</a></li>
                        <li><a title="تغییر کلمه عبور" href="https://www.cafeyab.com/user/password/">تغییر کلمه عبور</a></li>
                        <li><a title="تغییر آواتار" href="https://www.cafeyab.com/user/avatar/">تغییر آواتار</a></li>
                        <li><a title="به روز کردن پروفایل پایه" href="https://www.cafeyab.com/user/profile/edit.profile/group/7">به روز کردن پروفایل پایه</a></li>
                        <li><a title="به روز کردن اطلاعات ثبت سفارش" href="https://www.cafeyab.com/user/profile/edit.profile/group/8">به روز کردن اطلاعات ثبت سفارش</a></li>
                    </ul>
                </li>
                <?php if (isset($block['user']['message'])) { ?>
                    <li>
                        <a id="member-message" href="https://www.cafeyab.com/message" title="<?php echo _b('Message'); ?>">
                            <?php echo _b('Message'); ?> <span class="badge"><?php echo $block['user']['count']; ?></span>
                        </a>
                    </li>
                <?php } ?>
                <li>
                    <a href="<?php echo $block['user']['logout']; ?>" title="<?php echo _b('Logout'); ?>">
                        <i class="fa fa-sign-out"></i>
                        <?php echo _b('Logout'); ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php if ($modalEnabled && !$block['user']['uid']) {
    ob_start();
    include(Pi::path('module/system/template/block/partial/login-register-modal.phtml'));
    $modalContent = ob_get_clean();

    /* @var \Pi\View\Helper\FootScript $footScript */
    $footScript = $this->plugin('footScript');
    $footScript->addHtml($modalContent);
} ?>